import Head from 'next/head'

export default function AppMetaData() {
  return <Head>
    <title>Adaptation Reviews.</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
}